Main/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('accuont.urls')),
    path("app/",include('project.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accuont/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser,UserManager
# Create your models here.

class ManagerUSer(UserManager):
    
    def create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError("The Email must be set")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password, **extra_fields):
        """
        Create and save a SuperUser with the given email and password.
        """
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)
        extra_fields.setdefault("is_active", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")
        return self.create_user(email, password, **extra_fields)
        

class User(AbstractUser):
    type_enterprise = models.CharField(max_length=50,choices=(('علوم طبية','علوم طبية'),('علوم تطبيقية','علوم تطبيقية'),('علوم انسانية','علوم انسانية')),blank=True, null=True)
    company_name = models.CharField(max_length=50)
    point = models.IntegerField(default=0,null=True,blank=True)
    students = models.IntegerField(default=0)
    staff = models.IntegerField(default=0)
    
    manager = ManagerUSer
    def __str__(self):
        if self.is_superuser:
            return self.username
        return self.company_name    
class Depatment(models.Model):
    name = models.CharField(max_length=50)
    account = models.ForeignKey(User, on_delete=models.CASCADE)
    

project/models.py
from django.db import models
from accuont.models import Depatment,User
# Create your models here.
class Institution(models.Model):
    name = models.CharField('Name Institution', max_length=50)
    #created_at = models.DateTimeField(auto_now=False, auto_now_add=True)
    def __str__(self):
        return self.name
class Program(models.Model):
    name = models.CharField('Name Program', max_length=50)
    institution = models.ForeignKey(Institution,related_name='program', on_delete=models.CASCADE)
    def __str__(self):
        return self.name

class Quality_standards(models.Model):
    name = models.CharField('اسم المعيار', max_length=50)
    descripe = models.CharField('وصف المعيار',max_length=250,null=True,blank=True)
    
class AccStatus(models.Model):
    institution = models.ForeignKey(Institution,verbose_name='اسم المؤسسة',blank=True, null=True,on_delete=models.CASCADE)
    program = models.ForeignKey(Program,verbose_name='اسم القسم', on_delete=models.CASCADE)
    Accrediting_Body = models.CharField(verbose_name='نوع التقديم',max_length=50,choices=(('محلي','محلي'),('دولي','دولي')),blank=True, null=True)
    Accreditation_Status = models.CharField(verbose_name='حالة الاعتماد',max_length=50,choices=(('معتمد','معتمد'),('غير معتمد','غير معتمد'),('متقدمة للاعتماد','متقدمة للاعتماد'),('غير متقدمة للاعتماد','غير متقدمة للاعتماد')),blank=True, null=True)
    Accreditation_Start_Date = models.DateField(verbose_name='تاريخ بداية الاعتماد',auto_now=False, auto_now_add=False,blank=True, null=True)
    Accreditation_End_Date = models.DateField(verbose_name='تاريخ نهاية الاعتماد',auto_now=False, auto_now_add=False,blank=True, null=True)
    Compliance_Level = models.CharField(verbose_name='مستوى الامتثال',choices=(('High','High'),('Medium','Medium'),('Low','Low')),max_length=50,blank=True, null=True)
    Accreditation_Criteria = models.CharField(verbose_name='معايير الاعتماد',choices=(('A','A'),('B','B'),('C','C')),max_length=50,blank=True, null=True)
    # Progress_Towards_Accreditation = models.FileField(upload_to='Progress/Towards/Accreditation', max_length=100,blank=True, null=True)
    Self_Assessment_Reports = models.FileField(verbose_name='تقرير التقييم الذاتي',upload_to='Self-Assessment/Reports', max_length=100,blank=True, null=True)
    Site_Visit_Reports = models.FileField(verbose_name='تقرير زيادة الموقع',upload_to='Site/Visit/Reports', max_length=100,blank=True, null=True)
    Supporting_Documentation = models.FileField(verbose_name='التوثيق الداعم',upload_to='Supporting/Documentation', max_length=100,blank=True, null=True)
    
    

class AccStatusMain(models.Model):
    account = models.ForeignKey(User,verbose_name='اسم القسم',related_name='acc_main', on_delete=models.CASCADE)
    Accrediting_Body = models.CharField(verbose_name='نوع التقديم',max_length=50,choices=(('محلي','محلي'),('دولي','دولي')),blank=True, null=True)
    Accreditation_Status = models.CharField(verbose_name='حالة الاعتماد',max_length=50,choices=(('معتمد','معتمد'),('غير معتمد','غير معتمد'),('متقدمة للاعتماد','متقدمة للاعتماد'),('غير متقدمة للاعتماد','غير متقدمة للاعتماد')),blank=True, null=True)
    # Accreditation_Start_Date = models.DateField(verbose_name='تاريخ بداية الاعتماد',auto_now=False, auto_now_add=False,blank=True, null=True)
    # Accreditation_End_Date = models.DateField(verbose_name='تاريخ نهاية الاعتماد',auto_now=False, auto_now_add=False,blank=True, null=True)
    # Compliance_Level = models.CharField(verbose_name='مستوى الامتثال',choices=(('High','High'),('Medium','Medium'),('Low','Low')),max_length=50,blank=True, null=True)
    # Accreditation_Criteria = models.CharField(verbose_name='معايير الاعتماد',choices=(('A','A'),('B','B'),('C','C')),max_length=50,blank=True, null=True)
    # Progress_Towards_Accreditation = models.FileField(upload_to='Progress/Towards/Accreditation', max_length=100,blank=True, null=True)
    # Self_Assessment_Reports = models.FileField(verbose_name='تقرير التقييم الذاتي',upload_to='Self-Assessment/Reports', max_length=100,blank=True, null=True)
    # Site_Visit_Reports = models.FileField(verbose_name='تقرير زيادة الموقع',upload_to='Site/Visit/Reports', max_length=100,blank=True, null=True)
    # Supporting_Documentation = models.FileField(verbose_name='التوثيق الداعم',upload_to='Supporting/Documentation', max_length=100,blank=True, null=True)
    year = models.IntegerField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now=False, auto_now_add=True,blank=True, null=True)
    
class StandardAcc(models.Model):
    acc_status_main = models.ForeignKey(AccStatusMain,related_name='stan_acc', on_delete=models.CASCADE)
    quality_standards = models.ForeignKey(Quality_standards,on_delete=models.CASCADE)
    ratio = models.IntegerField(default=0)
    
class College_activities(models.Model):
    acc_status_main = models.ForeignKey(AccStatusMain,related_name='col_active', on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    year = models.IntegerField()
    type_activity = models.CharField(max_length=45,blank=True, null=True) 
    seasson = models.CharField(max_length=15)

templates/views/Acc.html
{% extends 'layouts/base.html' %}
{% block title %}
  Acc Status
{% endblock %}

{% block style %}
 <style>
  table th,td{
    padding: 20px;
    color: #fff;
  }
 </style>
{% endblock style %}
  
{% block content %}
<div class="card">
  <div class="card-body">
    <ul class="nav nav-pills">
      <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="#">الاعتماد المؤسسي</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">الاعتماد البرامجي</a>
      </li>
    </ul>
      <div >
        <table class="table table-bordered">
          <thead class="thead-dark">
            <tr>
              <th scope="col">الرقم</th>
              <th scope="col">العنوان</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>1</td>
              <td>معايير الاعتماد المؤسسي والبرامجي لمؤسسات التعليم العالي</td>
              <td><a href="https://qaa.ly/wp-content/uploads/2019/07/%D9%85%D8%B9%D8%A7%D9%8A%D9%8A%D8%B1-%D8%A7%D9%84%D8%A7%D8%B9%D8%AA%D9%85%D8%A7%D8%AF-%D8%A7%D9%84%D9%85%D8%A4%D8%B3%D8%B3%D9%8A-%D9%88%D8%A7%D9%84%D8%A8%D8%B1%D8%A7%D9%85%D8%AC%D9%8A-%D9%84%D9%85%D8%A4%D8%B3%D8%B3%D8%A7%D8%AA-%D8%A7%D9%84%D8%AA%D8%B9%D9%84%D9%8A%D9%85-%D8%A7%D9%84%D8%B9%D8%A7%D9%84%D9%8A-5.pdf">تحميل الملف</a></td>
            </tr>
            <tr>
              <td>2</td>
              <td>المستندات المطلوبة لغرض الحصول على الاعتماد المؤسسي لمؤسسات التعليم العالي</td>
              <td><a href="https://qaa.ly/wp-content/uploads/2019/07/%D9%82%D8%A7%D8%A6%D9%85%D8%A9-%D8%A7%D9%84%D9%85%D8%B3%D8%AA%D9%86%D8%AF%D8%A7%D8%AA-%D8%A7%D9%84%D9%85%D8%B7%D9%84%D9%88%D8%A8%D8%A9-%D9%84%D9%84%D8%AA%D8%AF%D9%82%D9%8A%D9%82-%D9%84%D9%84%D8%AA%D8%B9%D9%84%D9%8A%D9%85-%D8%A7%D9%84%D8%B9%D8%A7%D9%84%D9%8A1.pdf">تحميل الملف</a></td>
            </tr>
            <tr>
              <td>3</td>
              <td>الدراسة الذاتية</td>
              <td><a href="https://qaa.ly/wp-content/uploads/2019/07/%D8%A7%D9%84%D8%AF%D8%B1%D8%A7%D8%B3%D8%A9-%D8%A7%D9%84%D8%B0%D8%A7%D8%AA%D9%8A%D8%A9-2-7.pdf">تحميل الملف</a></td>
            </tr>
            <tr>
              <td>4</td>
              <td>دليل المعايير الاكاديمية للمقرر الدراسي توصيف المقرر</td>
              <td><a href="https://qaa.ly/wp-content/uploads/2023/08/2023-%D8%A7%D9%84%D9%85%D8%AA%D8%B7%D9%84%D8%A8%D8%A7%D8%AA-%D8%A7%D9%84%D8%A3%D9%83%D8%A7%D8%AF%D9%8A%D9%85%D9%8A%D8%A9-%D9%84%D9%84%D9%85%D9%82%D8%B1%D8%B1-%D8%A7%D9%84%D8%AF%D8%B1%D8%A7%D8%B3%D9%8A-1.docx">تحميل الملف</a></td>
            </tr>
            <tr>
              <td>5</td>
              <td>نموذج طلب الاعتماد المؤسسي لمؤسسات التعليم العالي</td>
              <td><a href="https://qaa.ly/wp-content/uploads/2023/08/%D9%86%D9%85%D9%88%D8%B0%D8%AC-%D8%B7%D9%84%D8%A8-%D8%A7%D9%84%D8%A7%D8%B9%D8%AA%D9%85%D8%A7%D8%AF-%D8%A7%D9%84%D9%85%D8%A4%D8%B3%D8%B3%D9%8A-2023-5-1.doc">تحميل الملف</a></td>
            </tr>
            <tr>
              <td>6</td>
              <td>دليل المعايير الاكاديمية للبرنامج الاكاديمي توصيف البرنامج</td>
              <td><a href="https://qaa.ly/wp-content/uploads/2023/08/%EF%BF%BD%D8%A7%D9%84%D9%85%D8%AA%D8%B7%D9%84%D8%A8%D8%A7%D8%AA-%D9%84%D9%84%D8%A8%D8%B1%D9%86%D8%A7%D9%85%D8%AC-%D8%A7%D9%84%D8%A3%D9%83%D8%A7%D8%AF%D9%8A%D9%85%D9%8A-%D8%A7%D9%84%D8%B9%D8%AF%D9%84-4-12-2017-1.doc">تحميل الملف</a></td>
            </tr>
          </tbody>
        </table>
    </div> 
  </div>
</div>

{% endblock %}

{% block script %}
  <script>
    $(function(){
      $('.nav-link').click(function(){
        $('.nav-link').removeClass('active')
        $(this).addClass('active')
      })
    })
  </script>
{% endblock script %}
  

templates/views/AccStatus.html
{% extends 'layouts/base.html' %}
{% block title %}
  Acc Status
{% endblock %}
{% block content %}
  <div class="table-responsive" style="overflow-y: scroll;max-height: 500px;">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>Institution Name</th>
          <th>Program Name</th>
          <th>Accrediting Body</th>
          <th>Accreditation Status</th>
          <th>Accreditation Start Date</th>
          <th>Accreditation End Date</th>
          <th>Compliance Level</th>
          <th>Accreditation Criteria</th>
          <th>Progress Towards Accreditation</th>
          <th>Self-Assessment Reports</th>
          <th>Site Visit Reports</th>
          <th>Supporting Documentation</th>
        </tr>
      </thead>
      <tbody>
        {% for val in AccStatus %}
          <tr>
            <td>{{ val.institution }}</td>
            <td>{{ val.program }}</td>
            <td>{{ val.Accrediting_Body }}</td>
            <td>{{ val.Accreditation_Status }}</td>
            <td>{{ val.Accreditation_Start_Date }}</td>
            <td>{{ val.Accreditation_End_Date }}</td>
            <td>{{ val.Compliance_Level }}</td>
            <td>{{ val.Accreditation_Criteria }}</td>
            <td>
              <a href="{{ val.Progress_Towards_Accreditation.url }}" class="btn btn-outline-success btn-sm">
                <i class="fas fa-file-pdf "></i>
              </a>
            </td>
            <td>
              <a href="{{ val.Self_Assessment_Reports.url }}" class="btn btn-outline-success btn-sm">
                <i class="fas fa-file-pdf"></i>
            </a>
            </td>
            <td>
              <a href="{{ val.Site_Visit_Reports.url }}" class="btn btn-outline-success btn-sm">
                <i class="fas fa-file-pdf"></i>
            </a>
            </td>
            <td>
              <a href="{{ val.Supporting_Documentation.url }}" class="btn btn-outline-success btn-sm">
                <i class="fas fa-file-pdf"></i>
            </a>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

templates/views/account.html
{% extends 'layouts/base.html' %}
{% block title %}
  المؤسسات
{% endblock %}
{% block content %}
  <div class="table-responsive" style="overflow-y: scroll;max-height: 500px;">
    <table class="table table-bordered text-right ">
      <thead>
        <tr>
          <th>اسم المؤسسة</th>
          <th>نوع المؤسسة</th>
          <th>اسم المستخدم</th>
          <th>البريد الالكتروني</th>
          <th>Control</th>
        </tr>
      </thead>
      <tbody>
        {% for val in users %}
          <tr>
            <td><a href="{% url 'department' val.id %}">{{ val.company_name }}</a></td>
            <td>{{ val.type_enterprise }}</td>
            <td>{{ val.username }}</td>
            <td>{{ val.email }}</td>
            <td>
                <a class="btn btn-sm btn-warning" href="{% url 'edit_account' val.id %}"><i class="fa fa-edit"></i></a>
                <a class="btn btn-sm btn-danger" href="{% url 'delete.account' val.id %}"><i class="fa fa-trash"></i></a>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

templates/views/create_AccStatus.html
{% extends 'layouts/base.html' %}

{% block title %}
  create AccStatus
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-md-8 m-auto">
      <div class="card">
        <div class="card-body">
          <h4 class="card-title">Create AccStatus</h4>
          <p class="card-description"></p>
          <form method="POST">
            {% csrf_token %}
            {% for field in form %}
              <div class="form-group">
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {{ field }}
                {% if field.errors %}
                  <div class="invalid-feedback">
                    {% for error in field.errors %}
                      {{ error }}
                    {% endfor %}
                  </div>
                {% endif %}
              </div>
            {% endfor %}
            <button type="submit" class="btn btn-success w-100 p-2">save</button>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

{% block script %}
  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
  <script>
    $('#id_program').html('')
    
    $('#id_institution').change(function () {
      axios.get("/app/get-program/" + $(this).val()).then((response) => {

        data = []
        $('#id_program').empty()
        response.data.data.map((res) => {
          data.push({ text: res.name, id: res.id })
        })
    
        $.each(data, function (index, item) {
          $('#id_program').append('<option value="' + item.id + '">' + item.text + '</option>')
        })
      })
    })
  </script>
{% endblock %}

templates/views/create_account.html
{% extends 'layouts/base.html' %}
{% block title %}
  Acc Status
{% endblock %}
{% block content %}
  <div class="row">
    <div class="col-md-8 m-auto">
      <div class="card">
        <div class="card-body" dir="rtl">
          <h4 class="card-title">اضافة مؤسسة</h4>
          <p class="card-description"></p>
          <form method="POST">
            {% csrf_token %}
            {% for field in form %}
              <div class="form-group">
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {{ field }}
                {% if field.errors %}
                  <div class="text-danger">
                    {% for error in field.errors %}
                      {{ error }}
                    {% endfor %}
                  </div>
                {% endif %}
              </div>
            {% endfor %}
            <button type="submit" class="btn btn-success w-100 p-2">save</button>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}
{% comment %} <form action="?type=one" method="POST" class="row add-device" enctype="multipart/form-data">
    <input type="hidden" name="type" value="one">
    {% csrf_token %}

    <p class="text-danger">The Service Tag You must enter only letters without using symbols</p>
    {{ form.as_div }}
    <section class="col-12 mt-4">
      {{ formfile }}
    </section>
    <p class="text-center">
      <button type="submit" class="btn btn-primary mt-4">Save</button>
    </p>
  </form> {% endcomment %}

templates/views/department.html
{% extends 'layouts/base.html' %}
{% block title %}
  المؤسسات
{% endblock %}
{% block content %}
  <div class="row">
    <div class="col-md-4">
      <div class="card">
        <div class="card-body" dir="rtl">
          <h4 class="card-title">اضافة قسم</h4>
          <p class="card-description"></p>
          <form method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_name">اسم القسم</label>
                <input type="text" name="name" maxlength="50" class="form-control" required="" id="id_name">
                <input type="hidden" name="account" value="{{ account.id }}">
              </div>
            <button type="submit" class="btn btn-success w-100 p-2">save</button>
          </form>
        </div>
      </div>
    </div>
    <div class="col-md-8">
        {% if messages %}
        <ul class="messages alert">
            {% for message in messages %}
            <li {% if message.tags %} class="text-success" {% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
      <div class="table-responsive">
        <table class="table table-bordered text-right">
          <thead>
            <tr>
            <th>اسم القسم</th>
              <th>اسم المؤسسة</th>

              <th>Control</th>
            </tr>
          </thead>
          <tbody>
            {% for val in account.depatment_set.all %}
              <tr>
                <td>{{ val.name }}</td>
                <td>{{ val.account.company_name }}</td>
                <td>
                  {% comment %} <a class="btn btn-sm btn-warning" href="?id={{ val.id }}"><i class="fa fa-edit"></i></a> {% endcomment %}
                  <a class="btn btn-sm btn-danger" href="{% url 'delete.department' val.id %}"><i class="fa fa-trash"></i></a>
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
{% endblock %}

templates/views/edit_account.html
{% extends 'layouts/base.html' %}
{% block title %}
  تعديل
{% endblock %}
{% block content %}
  <div class="row">
    <div class="col-md-8 m-auto">
      <div class="card">
        <div class="card-body" dir="rtl">
          <h4 class="card-title">تعديل بيانات مؤسسة</h4>
          <p class="card-description"></p>
          <form method="POST">
            {% csrf_token %}
            {% for field in form %}
              <div class="form-group">
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {{ field }}
              
                {% if field.errors %}
                  <div class="text-danger">
                    {% for error in field.errors %}
                      {{ error }}
                    {% endfor %}
                  </div>
                {% endif %}
              </div>
            {% endfor %}
            <button type="submit" class="btn btn-success w-100 p-2">تعديل</button>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}
{% comment %} <form action="?type=one" method="POST" class="row add-device" enctype="multipart/form-data">
    <input type="hidden" name="type" value="one">
    {% csrf_token %}

    <p class="text-danger">The Service Tag You must enter only letters without using symbols</p>
    {{ form.as_div }}
    <section class="col-12 mt-4">
      {{ formfile }}
    </section>
    <p class="text-center">
      <button type="submit" class="btn btn-primary mt-4">Save</button>
    </p>
  </form> {% endcomment %}

templates/views/login.html
{% load static %}
<!DOCTYPE html>
<html lang="ar" dir="rtl">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title></title>
    <title>تسجيل الدخول</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="{% static 'assets/vendors/mdi/css/materialdesignicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/vendors/css/vendor.bundle.base.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Changa:wght@200..800&display=swap" rel="stylesheet">
    <!-- endinject -->
    <!-- Plugin css for this page -->
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <!-- endinject -->
    <!-- Layout styles -->
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <!-- End layout styles -->
    <link rel="shortcut icon" href="{% static 'assets/images/favicon.png' %}" />
    <style>
      @import url("https://fonts.googleapis.com/css2?family=Poppins:wght@500;600;700&display=swap");
@import url('https://fonts.googleapis.com/css2?family=Roboto+Mono:ital,wght@0,100..700;1,100..700&display=swap');

.card{
    width: auto;
    height: auto;
    background-color: white;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    padding: 20px;
    border-radius: 20px;
}

.card h2{
  margin-bottom: 10px;
}

.card a.fp{
  width: 100%;
  display: flex;
  color: #5881D0;
}

.login_register{
      /* display: flex; */
      width: 100%;
      border: 1px solid rgba(221, 221, 221, 1);
      border-radius: 15px;
      margin: 20px 0;
      text-align: center;
}

.login_register a{
  font-size: 1em;
  padding: 10px 55px;
  border: none;
  width: 50%;
}

.login_register a.login{
  border-radius: 15px;
  background: linear-gradient(90deg, #003A74, #006AD5);
  color: white;
}

.login_register a.register{
  border-radius: 15px;
  background-color: transparent;
  color: black;
}

.form{
  display: flex;
  flex-direction: column;
  width: 100%;
}

.form input{
  padding: 10px;
  border-radius: 5px;
  border: 1px solid #DDDDDD;
  color: #A0A6A3;
  font-family: "Roboto Mono", sans-serif;
  box-shadow: 1px 5px 9px rgba(211, 211, 211, .7);
}

.form input.email{
  margin-bottom: 15px;
}

.form input.pass{
  margin-bottom: 5px;
}

.login_btn{
  font-size: 20px;
  color: white;
  border-radius: 15px;
  border: none;
  background-color: #003A74;
  width: 100%;
  padding: 10px;
  margin-top: 15px;
  margin-bottom: 15px;
  background: linear-gradient(-90deg, #003A74, #006AD5);
  box-shadow: 1px 5px 9px rgba(211, 211, 211, .9);
}

.footer_card{
  display: flex;
  width: 100%;
  justify-content: center;
}

.footer_card p{
  margin-right: 10px;
}

.footer_card a{
  color: #5881D0;
}
    </style>
  </head>
  <body>
    <div class="container-scroller">
      <div class="container-fluid page-body-wrapper full-page-wrapper">
        <div class="row w-100 m-0">
          <div class="content-wrapper full-page-wrapper auth login-bg"  style="background-image: url({% static 'assets/images/bg.jpg' %});">
            
            <div class="col-md-4 mt-5">
            

            <div class="card py-5">
              <h2 style="color: #003A74; text-align: center;">لوحة معلومات جامعة سبها</h2>
      
                  <!-- SE CONNECTER / S'INSCRIRE -->
              <div class="login_register">
                  <a href="
      https://codepen.io/pen?template=gOEqMVq
      " class="login" target="blank">تسجيل الدخول</a>
                  
              </div>
      
                  <!-- FORMULAIRE -->
              <form class="form" action="" method="post">
                {% csrf_token %}
                <label>اسم المستخدم *</label>
                  <input type="text" placeholder="اسم المستخدم" class="email" name="username" required>
                  <label>كلمة المرور *</label>
                  <input type="password" placeholder="كلمة المرور" class="pass" name="password" required>
                  <button type="submit" class="login_btn">الدخول</button>
              </form>
      
                  <!-- MOT DE PASSE OUBLIE ? -->
              
      
                  <!-- BOUTTON LOGIN -->
                  
      
                  <!-- PIED DE LA CARD -->
             
            </div>
            <div class="col-md-8">
            </div>
            </div>
          </div>
          <!-- content-wrapper ends -->
        </div>
        <!-- row ends -->
      </div>
      <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
    <!-- plugins:js -->
    <script src="{% static 'assets/vendors/js/vendor.bundle.base.js' %}"></script>
    <!-- endinject -->
    <!-- Plugin js for this page -->
    <!-- End plugin js for this page -->
    <!-- inject:js -->
    <script src="{% static 'assets/js/off-canvas.js' %}"></script>
    <script src="{% static 'assets/js/hoverable-collapse.js' %}"></script>
    <script src="{% static 'assets/js/misc.js' %}"></script>
    <script src="{% static 'assets/js/settings.js' %}"></script>
    <script src="{% static 'assets/js/todolist.js' %}"></script>
    <!-- endinject -->
  </body>
</html>