Main/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('accuont.urls')),
    path("app/",include('project.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accuont/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser,UserManager
# Create your models here.

class ManagerUSer(UserManager):
    
    def create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError("The Email must be set")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password, **extra_fields):
        """
        Create and save a SuperUser with the given email and password.
        """
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)
        extra_fields.setdefault("is_active", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")
        return self.create_user(email, password, **extra_fields)
        

class User(AbstractUser):
    type_enterprise = models.CharField(max_length=50,choices=(('علوم طبية','علوم طبية'),('علوم تطبيقية','علوم تطبيقية'),('علوم انسانية','علوم انسانية')),blank=True, null=True)
    company_name = models.CharField(max_length=50)
    point = models.IntegerField(default=0,null=True,blank=True)
    students = models.IntegerField(default=0)
    staff = models.IntegerField(default=0)
    
    manager = ManagerUSer
    def __str__(self):
        if self.is_superuser:
            return self.username
        return self.company_name    
class Depatment(models.Model):
    name = models.CharField(max_length=50)
    account = models.ForeignKey(User, on_delete=models.CASCADE)
    

templates/views/admin/AccStatus.html
{% extends 'layouts/base.html' %}
{% block title %}
  Acc Status
{% endblock %}
{% block content %}
{% if messages %}
            <ul class="messages alert">
                {% for message in messages %}
                <li {% if message.tags %} class="text-success" {% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
          {% endif %}
          <div class="card">
            <div class="card-body">
              <div class="table-responsive" style="overflow-y: scroll;max-height: 500px;">
                <table class="table table-bordered">
                  <thead>
                    <tr>
                      <th>اسم المؤسسة</th>
                      <th>نوع التقديم</th>
                      <th>حالة الاعتماد</th>
                      <th>العام الدراسي</th>
                      <th>الانشطة</th>
                      <th>created at</th>
                      {% comment %} <th>contorl</th> {% endcomment %}
                    </tr>
                  </thead>
                  <tbody>
                    {% for val in AccStatus %}
                      <tr>
                        <td>{{ val.account.company_name }}</td>
                        <td>{{ val.Accrediting_Body }}</td>
                        <td>{{ val.Accreditation_Status }}</td>
                        <td>{{ val.year }}</td>
                        <td><a href="{% url 'create_college_activities' val.id %}">انشطة المؤسسة</a></td>
                        <td>{{ val.created_at }}</td>
                        <td>
                          <a href="{% url 'edit_Acc' val.id %}" class="btn btn-warning"><i class="fa fa-edit"></i></a>
                          <a href="{% url 'delete_acc' val.id %}" class="btn btn-danger"><i class="fa fa-trash"></i></a>
                        </td> 
                      </tr>
                    {% endfor %}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
 
{% endblock %}

templates/views/admin/Evaluation.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block style %}

{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-lg-12 grid-margin stretch-card">
      <div class="card" style="background-color: #fff;">
        <div class="card-header">
          <h4 class="card-title text-dark">تقييم المستخدمين للوحة المعلومات </h4>
          
        </div>
        <div class="card-body">
          {% comment %} <h4 class="card-title">Bar chart</h4> {% endcomment %}
          <div>
          <h3>معيار 1</h3>
          <canvas id="chart1" width="400" height="200"></canvas>
        </div>
        <div>
            <h3>معيار 2</h3>
            <canvas id="chart2" width="400" height="200"></canvas>
        </div>
        <div>
            <h3>معيار 3</h3>
            <canvas id="chart3" width="400" height="200"></canvas>
        </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

{% block script %}
<script src="{% static 'assets/js/chart.js' %}"></script>
<script src="https://unpkg.com/chartjs-gauge@0.3.0/dist/chartjs-gauge.js"></script>

<script>
    var criteriaData = {{ criteria_data|safe }};
    var labels = {{ labels | safe}};
    var colors = [
        'rgba(255, 99, 132, 0.2)',
        'rgba(54, 162, 235, 0.2)',
        'rgba(255, 206, 86, 0.2)',
        'rgba(75, 192, 192, 0.2)',
        'rgba(153, 102, 255, 0.2)'
    ];
    var borderColors = [
        'rgba(255, 99, 132, 1)',
        'rgba(54, 162, 235, 1)',
        'rgba(255, 206, 86, 1)',
        'rgba(75, 192, 192, 1)',
        'rgba(153, 102, 255, 1)'
    ];

    degree = {1:'موافق بشدة',2:'موافق',3:'محايد',4:'غير موافق',5:'غير موافق بشده'}
    function createChart(ctx, data, label,labels_d) {
        var datasets = Object.keys(data).map((key, index) => {
            return {
                label: degree[key] + key,
                data: data[key],
                backgroundColor: colors[index],
                borderColor: borderColors[index],
                borderWidth: 1
            };
        });

        new Chart(ctx, {
            type: 'bar',
            data: {
                labels: labels_d,
                datasets: datasets
            },
            options: {
                scales: {
                    y: {
                        beginAtZero: true
                    }
                }
            }
        });
    }

    createChart(document.getElementById('chart1').getContext('2d'), criteriaData.criteria1, 'معيار 1',labels.criteria1);
    createChart(document.getElementById('chart2').getContext('2d'), criteriaData.criteria2, 'معيار 2',labels.criteria2);
    createChart(document.getElementById('chart3').getContext('2d'), criteriaData.criteria3, 'معيار 3',labels.criteria3);
</script>
{% endblock %}

templates/views/admin/create_AccStatus.html
{% extends 'layouts/base.html' %}

{% block title %}
  create AccStatus
{% endblock %}
{% block style %}
<style>
  .form-group div div{
    display: inline !important;
  }
  /* The h1's container */

</style>
{% endblock style %}
{% block content %}
  <div class="row">
    <div class="col-md-8 m-auto">
      
      <div class="card">
        <div class="card-body">
          <h4 class="card-title">نموذج الاعتماد</h4>
          <p class="card-description">
            {% if messages %}
            <ul class="messages alert">
                {% for message in messages %}
                <li {% if message.tags %} class="text-success" {% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
          {% endif %}
          </p>
          <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {% comment %} <div class="form-group">
              <select id="account" class="form-control">
                <option>select</option>
                {% for val in account %}
                  <option value="{{ val.id }}">{{ val.company_name }}</option>
                {% endfor %}
                  
              </select>
            </div> {% endcomment %}
            {% if user.is_superuser %}
            <div class="form-group">

              <label for="id_account">اسم المؤسسة</label>
                <select name="account" class="form-control" required="" id="id_account">
                  <option value="" selected="">---------</option>
                  {% for val in account %}
                    <option value="{{ val.id }}">{{ val.company_name }}</option>
                  {% endfor %}
                </select>
            </div>
            {% else %}
            <input type="hidden" name="account" value="{{ user.id }}">
            {% endif %}
            {% for field in form %}
              <div class="form-group">
                
                {% if field.label == 'Year' %}
                <label>العام</label>
                <select name="year" class="form-control" required>
                
                  {% for val in years %}
                    <option value="{{ val }}">{{ val }}</option>
                  {% endfor %}
                    
                </select>
                {% else %}
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {{ field }}
                {% endif %}
                {% if field.errors %}
                  <div class="invalid-feedback">
                    {% for error in field.errors %}
                      {{ error }}
                    {% endfor %}
                  </div>
                {% endif %}
              </div>
            {% endfor %}
            <hr>
            <div class="form-group">
              
              
            </div>
            <div >
              <label>نسبة انجاز الكلية لمعايير اعتماد المؤسسي</label>
            
            <div id="show-result" class="row mb-3">
              {% for val in quality_standards %}
              <div class="col-4">
                <label>{{ val.name }}</label>
                <input type="hidden" value="{{ val.id }}" class="form-control" name="quality_standards[]" >
                {% comment %} <div class="input-group"> {% endcomment %}
                  <div class="input-group">
                    
                  <input type="number" max="100" min="0" class="form-control" name="ratio[]" required>
                  <span class="input-group-text" id="basic-addon1">%</span>
                  </div>
                    
                  
                {% comment %} </div> {% endcomment %}
                
              </div>
              {% endfor %}
            </div>
          </div>
          
            <button type="submit" class="btn btn-success w-100 p-2">save</button>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

{% block script %}
  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
  <script>
    $('#id_department').html('')
    
    $('#account').change(function () {
      axios.get("/app/get-department/" + $(this).val()).then((response) => {

        data = []
        $('#id_department').empty()
        response.data.data.map((res) => {
          data.push({ text: res.name, id: res.id })
        })
    
        $.each(data, function (index, item) {
          $('#id_department').append('<option value="' + item.id + '">' + item.text + '</option>')
        })
      })
    })
  </script>
{% endblock %}

templates/views/admin/create_collage_active.html
{% extends 'layouts/base.html' %}

{% block title %}
  انشطة المؤسسة
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-md-6">
      
      <div class="card">
        <div class="card-body">
          <h4 class="card-title"> انشطة الكلية في مجال الجودة</h4>
          <p class="card-description">
            {% if messages %}
            <ul class="messages alert">
                {% for message in messages %}
                <li {% if message.tags %} class="text-success" {% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
          {% endif %}
          </p>
          <form method="POST" action="">
            {% csrf_token %}
        
            <div class="form-group">
              <label>ورش العمل والمحاضرات المنجزة</label>
              <label>النوع</label><br>
              <label>ورشة عمل <input type="radio" name="type" value="ورشة عمل"/></label>
              <label>محاضرة <input type="radio" name="type" value="محاضرة"/></label>
            </div>
            <div class="form-group">
              <label>العام</label>
              <select name="year" class="form-control" required>
                
                {% for val in years %}
                  <option value="{{ val }}">{{ val }}</option>
                {% endfor %}
                  
              </select>
            </div>
            <div class="form-group">
              <label>الفصل</label><br>
              <label>خريف <input type="radio" name="seasson" value="خريف"/></label>
              <label>ربيع <input type="radio" name="seasson" value="ربيع"/></label>
            </div>
            <div class="form-group">
              <label>االعنوان</label>
              <input type="text" class="form-control" required name="name">
            </div>
            <button type="submit" class="btn btn-success w-100 p-2">حفظ</button>
          </form>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="card">
        <div class="card-header">
          <p class="card-title">
            {{ acc.account.company_name }}
          </p>
        </div>
        <div class="card-body">
          <div class="table-responsive" style="overflow-y: scroll;max-height: 500px;">
            <table class="table table-bordered">
              <thead>
                <tr>
                  <th>العنوان</th>
                  <th>النوع</th>
                  <th>العام</th>
                  <th>الفصل</th>
                  <th>control</th>
                </tr>
              </thead>
              <tbody>
                
                {% for val in college_active %}
                <tr>
                  <td>{{ val.name }}</td>
                  <td>{{ val.type_activity }}</td>
                  <td>{{ val.year }}</td>
                  <td>{{ val.seasson }}</td>
                  <td>
                    <a class="btn btn-danger" href="{% url 'delete_college_activities' val.id %}">
                      <i class="fa fa-trash"></i>
                    </a>
                  </td>
                </tr>
                {% endfor %}
        
              </tbody>
            </table>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

{% block script %}
  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>

{% endblock %}

templates/views/admin/edit_AccStatus.html
{% extends 'layouts/base.html' %}

{% block title %}
  create AccStatus
{% endblock %}
{% block style %}
<style>
  .form-group div div{
    display: inline !important;
  }
  /* The h1's container */

</style>
{% endblock style %}
{% block content %}
  <div class="row">
    <div class="col-md-8 m-auto">
      
      <div class="card">
        <div class="card-body">
          <h4 class="card-title">نموذج الاعتماد</h4>
          <p class="card-description">
            {% if messages %}
            <ul class="messages alert">
                {% for message in messages %}
                <li {% if message.tags %} class="text-success" {% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
          {% endif %}
          </p>
          <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {% comment %} <div class="form-group">
              <select id="account" class="form-control">
                <option>select</option>
                {% for val in account %}
                  <option value="{{ val.id }}">{{ val.company_name }}</option>
                {% endfor %}
                  
              </select>
            </div> {% endcomment %}
            {% comment %} {% if user.is_superuser %}
            <div class="form-group">

              <label for="id_account">اسم المؤسسة</label>
                <select name="account" class="form-control" required="" id="id_account">
                  <option value="" selected="">---------</option>
                  {% for val in account %}
                    <option value="{{ val.id }}">{{ val.company_name }}</option>
                  {% endfor %}
                </select>
            </div>
            {% else %}
            <input type="hidden" name="account" value="{{ user.id }}">
            {% endif %} {% endcomment %}
            {% for field in form %}
              <div class="form-group">
                
                {% if field.label == 'Year' %}
                <label>العام</label>
             
                <select name="year" class="form-control" required>
                
                  {% for val in years %}
                    <option value="{{ val }}" {% if val == field.value %}selected{% endif %}>{{ val }}</option>
                  {% endfor %}
                    
                </select>
                {% else %}
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {{ field }}
                {% endif %}
                {% if field.errors %}
                  <div class="invalid-feedback">
                    {% for error in field.errors %}
                      {{ error }}
                    {% endfor %}
                  </div>
                {% endif %}
              </div>
            {% endfor %}
            <hr>
            <div class="form-group">
              
              
            </div>
            <div >
              <label>نسبة انجاز الكلية لمعايير اعتماد المؤسسي</label>
            
            <div id="show-result" class="row mb-3">
              {% for val in quality_standards %}
              <div class="col-4">
                <label>{{ val.quality_standards.name }}</label>
                <input type="hidden" value="{{ val.quality_standards.id }}" class="form-control" name="quality_standards[]" >
                {% comment %} <div class="input-group"> {% endcomment %}
                  <div class="input-group">
                    
                  <input type="number" max="100" min="0" class="form-control" value="{{ val.ratio }}" name="ratio[]" required>
                  <span class="input-group-text" id="basic-addon1">%</span>
                  </div>
                    
                  
                {% comment %} </div> {% endcomment %}
                
              </div>
              {% endfor %}
            </div>
          </div>
          
            <button type="submit" class="btn btn-success w-100 p-2">save</button>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

{% block script %}
  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
  <script>
    $('#id_department').html('')
    
    $('#account').change(function () {
      axios.get("/app/get-department/" + $(this).val()).then((response) => {

        data = []
        $('#id_department').empty()
        response.data.data.map((res) => {
          data.push({ text: res.name, id: res.id })
        })
    
        $.each(data, function (index, item) {
          $('#id_department').append('<option value="' + item.id + '">' + item.text + '</option>')
        })
      })
    })
  </script>
{% endblock %}

templates/views/admin/edit_acc.html
{% extends 'layouts/base.html' %}

{% block title %}
  create AccStatus
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-md-8 m-auto">
      
      <div class="card">
        <div class="card-body">
          <h4 class="card-title">Edit AccStatus</h4>
          <p class="card-description">
            {% if messages %}
            <ul class="messages alert">
                {% for message in messages %}
                <li {% if message.tags %} class="text-success" {% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
          {% endif %}
          </p>
          <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {% if user.is_superuser %}
            <div class="form-group">
              <select name="account" class="form-control" required="" id="id_account">
                <option>select</option>
                {% for val in account %}
                  <option value="{{ val.id }}"  {% if val.id == acc.account.id %} selected {% endif %}>{{ val.company_name }}</option>
                {% endfor %}
              </select>
            </div>
            {% else %}
            <input type="hidden" name="account" value="{{ user.id }}">
            {% endif %}
            {% for field in form %}
              <div class="form-group">
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {{ field }}
                {% if field.errors %}
                  <div class="invalid-feedback">
                    {% for error in field.errors %}
                      {{ error }}
                    {% endfor %}
                  </div>
                {% endif %}
              </div>
            {% endfor %}
            <button type="submit" class="btn btn-success w-100 p-2">save</button>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

{% block script %}
  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
  <script>
    $('#id_department').html('')
    
    function change(id){
      axios.get("/app/get-department/" + id).then((response) => {

        data = []
        $('#id_department').empty()
        response.data.data.map((res) => {
          data.push({ text: res.name, id: res.id })
        })
        $('#id_department').append('<option value=""> choise </option>')
        $.each(data, function (index, item) {
          $('#id_department').append('<option value="' + item.id + '">' + item.text + '</option>')
        })
      })
    }
    $('#account').change(function () {
      change($(this).val())
    })

    change({{ acc.department.account.id }})
  </script>
{% endblock %}

templates/views/admin/quality_standards.html
{% extends 'layouts/base.html' %}
{% block title %}
  Acc Status
{% endblock %}

{% block content %}
<div class="card">
  <div class="card-header">
    <a class="btn btn-outline-primary" href="{% url 'quality_standard.create' %}">معييار جديد</a>
  </div>
  <p class="card-description">
    {% if messages %}
    <ul class="messages alert">
        {% for message in messages %}
        <li {% if message.tags %} class="text-success" {% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
  {% endif %}
  </p>
  <div class="card-body"  style="overflow-y: scroll;max-height: 500px;">
    <div class="table-responsive">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>الاسم</th>
            <th>الوصف</th>
            <th>contorl</th>
          </tr>
        </thead>
        <tbody>
          {% for val in Quality_standards %}
            <tr>
              <td>{{ val.name }}</td>
              <td>{{ val.descripe }}</td>
              <td>
                <a href="{% url 'quality_standard.delete' val.id %}" class="btn btn-outline-danger"><i class="fa fa-trash"></i></a>
                <a href="{% url 'quality_standard.edit' val.id %}" class="btn btn-outline-warning"><i class="fa fa-edit"></i></a>
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>
  
{% endblock %}

templates/views/admin/quality_standards_create.html
{% extends 'layouts/base.html' %}

{% block title %}
  معييار جديد
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-md-8 m-auto">
      
      <div class="card">
        <div class="card-body">
          <h4 class="card-title">معييار جديد</h4>
          <p class="card-description">
            {% if messages %}
            <ul class="messages alert">
                {% for message in messages %}
                <li {% if message.tags %} class="text-success" {% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
          {% endif %}
          </p>
          <form method="POST" action="">
            {% csrf_token %}
        
            {% for field in form %}
              <div class="form-group">
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {{ field }}
                {% if field.errors %}
                  <div class="invalid-feedback">
                    {% for error in field.errors %}
                      {{ error }}
                    {% endfor %}
                  </div>
                {% endif %}
              </div>
            {% endfor %}
            <button type="submit" class="btn btn-success w-100 p-2">حفظ</button>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

{% block script %}
  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>

{% endblock %}

templates/views/admin/quality_standards_edit.html
{% extends 'layouts/base.html' %}

{% block title %}
تعديل بيانات المعايير 
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-md-8 m-auto">
      
      <div class="card">
        <div class="card-body">
          <h4 class="card-title">تعديل بيانات المعايير </h4>
          <p class="card-description">
            {% if messages %}
            <ul class="messages alert">
                {% for message in messages %}
                <li {% if message.tags %} class="text-success" {% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
          {% endif %}
          </p>
          <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
           
            {% for field in form %}
              <div class="form-group">
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {{ field }}
                {% if field.errors %}
                  <div class="invalid-feedback">
                    {% for error in field.errors %}
                      {{ error }}
                    {% endfor %}
                  </div>
                {% endif %}
              </div>
            {% endfor %}
            <button type="submit" class="btn btn-success w-100 p-2">حفظ</button>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

{% block script %}
  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>

{% endblock %}